### ISSUE TITLE
small windows format parse bug

### ISSUE THREAD

**Issue by wmnwmn** [groupschoof/AHRD#10]
Query sequence headers of this form are not parsed right:
`>Acession\r\n`
i.e., they have the windows-style newlines, and no other whitespace.

I will be submitting a fix on this issue.

**Comment by groupschoof** [comment]
Dear wmnwmn, 

thank you very much for bringing this up and proposing a fix. Based on your suggestion I implemented a similar, slightly more flexible solution. It is now included in tag v3.3.2 (latest master). 

Cheers!
