### ISSUE TITLE
Interproscan compatibility

### ISSUE THREAD

**Issue by wmnwmn** [groupschoof/AHRD#13]
The readme doesn't say much about interproscan but it doesn't seem to work with the current version.
There are a couple of issues:
1) None of the currently supported interpro analysis types provide an output with an Interpro-ID like IPR000536
2) The example ahrd_input.yml specifies a file interpro_31.xml but I don't see where to get this file (or an updated version) from interpro

**Comment by groupschoof** [comment]
Dear wmnwmn, 

AHRD's support for InterPro annotations is deprecated. We discourage its usage. In any way AHRD did not do more than filter each query protein's IPR annos for the most informatives discarding semantically included parents and the such.

Cheers!
