### ISSUE TITLE
Author name correction

### ISSUE THREAD

**Issue by gsrnivas** [groupschoof/AHRD#20]
@asishallab @groupschoof 

It is nice to see how this project has evolved. Many thanks for adding my contribution to the authors list. Could you please change my name Dr. Sri Girish to Dr. Girish Srinivas. in the readme file? Many thanks!

Corrected one would read like:
Dr. Asis Hallab, Kathrin Klee, Florian Boecker, Dr. Girish Srinivas, and Prof. Dr. Heiko Schoof

**Comment by FlorianBoecker** [comment]
Hello Girish,

thanks for the info!
I fixed it.

Best,
Florian
