### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by holmrenser** [groupschoof/AHRD#4]
AHRD does not seem to be able to parse blast+ 2.2.31 pairwise output. 
Are there any plans on updating the blast parser?

**Comment by groupschoof** [comment]
Dear holmrenser, thank you for your input. In fact we have developed a Blast+ parser in a different branch. Now master has been merged and you can use Blast+ and are no longer restricted to legacy Blast. In fact AHRD is now able to read any tabular sequence similarity search output, as long as it contains the required information. See the latest documentation (README.textile) for details, and please note, that AHRD now requires tabular search results. "Blast pairwise" is no longer supported.
