### ISSUE TITLE
GO from only one hit?

### ISSUE THREAD

**Issue by wmnwmn** [groupschoof/AHRD#5]
This is maybe more of a question than an issue...
if I understand correctly the GO annotation is pulled only from the single hit which is selected for the HRD. 
My concern is that GO annotation is fairly sparse in the UniprotKB, so the hit having the best HRD may not have any GO listed, even though other hits to have meaningful GO annotation. Is there a plan or possibility of selecting the GOs from more than one hit?

**Comment by groupschoof** [comment]
You are right, this is a question and not an issue.

- According to our latest findings the GO annotation based on this performs very well. If annotating GO is your main concern, you should search only Swissprot and not the whole of Uniprot, thus excluding trEMBL. In doing so, almost all hits will have GO annotations to be used by AHRD. 
- There is an option to extend the transferred GO terms with all parental GO terms. In doing so you compensate for some of the sparsity of the GO annotations available in UniprotKB. That is the sparsity of the annotation depth of reference proteins.
- In the future we might extend AHRD to select the highest scoring candidate for the human readable description and if this candidate does not have GO annotations select the highest scoring candidate WITH GO annotations to annotate GO terms to the query.
