### ISSUE TITLE
build problem with comment characters

### ISSUE THREAD

**Issue by wmnwmn** [groupschoof/AHRD#6]
Using OpenJDK javac 1.8.0_77  and ant 1.9.4, I am hitting problems with several characters in comments. Deleting these, I am able to compile. Platform is FreeBSD 9.3:

[javac] Compiling 30 source files to /home/wmn/AHRD/classes
    [javac] /home/wmn/AHRD/src/ahrd/model/BlastResult.java:90: error: unmappable character for encoding ASCII
    [javac]      * Makes a double string representation parseable by Double.parseDouble(???).
    [javac]                                                                             ^
    [javac] /home/wmn/AHRD/src/ahrd/model/BlastResult.java:90: error: unmappable character for encoding ASCII
    [javac]      * Makes a double string representation parseable by Double.parseDouble(???).
    [javac]                                                                              ^
    [javac] /home/wmn/AHRD/src/ahrd/model/BlastResult.java:90: error: unmappable character for encoding ASCII
    [javac]      * Makes a double string representation parseable by Double.parseDouble(???).
    [javac]                                                                               ^
    [javac] /home/wmn/AHRD/src/ahrd/model/BlastResult.java:285: error: unmappable character for encoding ASCII
    [javac]      * Proteins. See function <code>generateHRDCandidateForProtein(???)</code> for
    [javac]                                                                    ^
    [javac] /home/wmn/AHRD/src/ahrd/model/BlastResult.java:285: error: unmappable character for encoding ASCII
    [javac]      * Proteins. See function <code>generateHRDCandidateForProtein(???)</code> for
    [javac]                                                                     ^
    [javac] /home/wmn/AHRD/src/ahrd/model/BlastResult.java:285: error: unmappable character for encoding ASCII
    [javac]      * Proteins. See function <code>generateHRDCandidateForProtein(???)</code> for
    [javac]                                                                      ^
    [javac] /home/wmn/AHRD/src/ahrd/model/BlastResult.java:307: error: unmappable character for encoding ASCII
    [javac]      * BlastResult and subsequently the method 'Protein.addBlastResult(???)' is
    [javac]                                                                        ^
    [javac] /home/wmn/AHRD/src/ahrd/model/BlastResult.java:307: error: unmappable character for encoding ASCII
    [javac]      * BlastResult and subsequently the method 'Protein.addBlastResult(???)' is
    [javac]                                                                         ^
    [javac] /home/wmn/AHRD/src/ahrd/model/BlastResult.java:307: error: unmappable character for encoding ASCII
    [javac]      * BlastResult and subsequently the method 'Protein.addBlastResult(???)' is
    [javac]                                                                          ^
    [javac] /home/wmn/AHRD/src/ahrd/model/EvaluationScoreCalculator.java:126: error: unmappable character for encoding ASCII
    [javac]      * f-beta-score := (1+beta??) * (pr * rc) / (beta??*pr + rc)
    [javac]                               ^
    [javac] /home/wmn/AHRD/src/ahrd/model/EvaluationScoreCalculator.java:126: error: unmappable character for encoding ASCII
    [javac]      * f-beta-score := (1+beta??) * (pr * rc) / (beta??*pr + rc)
    [javac]                                ^
    [javac] /home/wmn/AHRD/src/ahrd/model/EvaluationScoreCalculator.java:126: error: unmappable character for encoding ASCII
    [javac]      * f-beta-score := (1+beta??) * (pr * rc) / (beta??*pr + rc)
    [javac]                                                      ^
    [javac] /home/wmn/AHRD/src/ahrd/model/EvaluationScoreCalculator.java:126: error: unmappable character for encoding ASCII
    [javac]      * f-beta-score := (1+beta??) * (pr * rc) / (beta??*pr + rc)

**Comment by groupschoof** [comment]
Please send a pull request

**Comment by asishallab** [comment]
Dear @wmnwmn, please do send a github pull request. We do not have OpenJDK installed, so it is impossible for us to test any corrections of special characters in the comments. To create a pull request is very easy and does not take more than 1 to 3 minutes. We would greatly appreciate the contribution. 
Have a look at github's docu: https://help.github.com/articles/using-pull-requests/

Thanks a lot

**Comment by wmnwmn** [comment]
Ok I will. I never did a pull before, although I have done simple checkins to github on our own projects. 
But I would assume those comments got created by some process, and which needs to be examined to find out why it put special chars in the argument positions. (Note that you can see these characters by using od...I can't remember if they looked like unicode or something).
